clear all;
clc;
file_path = {
    'D:\Simple_Use\output\correct_poss01_1.txt';...
    'D:\Simple_Use\output\correct_poss01_2.txt';...
    'D:\Simple_Use\output\correct_poss01_3.txt';...
    'D:\Simple_Use\output\correct_poss01_4.txt';...
    'D:\Simple_Use\output\correct_poss01_5.txt';...
    'D:\Simple_Use\output\correct_poss01_6.txt';...
};
file_num = 6;
opt_choice_seq = Choose_Seq(file_path{file_num,1});
save_txt(opt_choice_seq',['D:\Simple_Use\output\opt_choice_seq_0' num2str(file_num) '.txt']);